### ISSUE TITLE
XML style

### ISSUE THREAD

**Issue by madmanali93** [madmanali93/dog-company#47]
http://dev.dog-company.com/?page_id=223
XML finally done. Once code is set on the new website all that is required is an empty page name SquadXML in wordpress. I am tired after coding this. I would love if you could style it. I would understand if you didn't want to.

**Comment by michael-letcher** [comment]
Is this fixed? I think not :)

**Comment by bradley-doyle** [comment]
Agreed, doesn't seem fixed to me 😃
